### PR TITLE
global: support for object tags

### PR DESCRIPTION
**Pull request by lnielsen**
Replacement for #167. See review in #167

### CODE REVIEW

**Comment by drjova** [comment]
hey, is it blocked by something else?

**Comment by ntarocco** [comment]
@drjova I discussed previously with Lars, he should check the PR at the next Invenio sprint, starting from 11th of February.

**Comment by drjova** [comment]
thanks!

**Comment by lnielsen** [comment]
🎉 🎸 🚀

**Comment by drjova** [comment]
🦄

**Comment by ntarocco** [comment]
👍 💯 thanks @lnielsen!

**Pull request merged**
