### PR TITLE
examples: fixture data for application

### PR DESCRIPTION
**Pull request by lnielsen**
* Adds fixture data for example application.

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

### CODE REVIEW

**Comment by drjova** [comment]
:+1: :+1:

**Comment by lnielsen** [comment]
@ddaze Would you mind doing a review?

**Comment by ddaze** [comment]
Looks good, also all Buckets and Objects are created/updated/deleted in the example app.

**Comment by egabancho** [comment]
Just update the copyright for `.travis.yml`, `invenio_files_rest/ext.py` and `examples/app.py` and :rocket:

**Comment by lnielsen** [comment]
Ready

**Pull request merged**
