### PR TITLE
global: removal of remaining Babel occurences

### LINKED ISSUE #4: Babel is missing from requirements
After installing the application,

I tried to run it with : 

```
python example/app.py
```

But crashed with output being :

```python
Traceback (most recent call last):
  File "examples/app.py", line 41, in <module>
    from flask_babelex import Babel
ImportError: No module named flask_babelex
```

### PR DESCRIPTION
**Pull request by PXke**
* Removes Babel in example/app.py and
  test/conftest.py. (closes #4)

Signed-off-by: Guillaume Lastecoueres <guillaume@tind.io>

### CODE REVIEW

**Comment by PXke** [comment]
Tackle the issue #4. Could you please have a look @lnielsen ?

**Comment by jirikuncar** [comment]
:shipit:

**Comment by PXke** [comment]
@jirikuncar thanks a lot !

**Comment by jirikuncar** [comment]
@PXke don't forget to add `(closes #4)` to commit message. Thanks

**Comment by PXke** [comment]
Sure ! I will add it!

**Comment by lnielsen** [comment]
I have a larger restructuring that I hope to push tomorrow. Please be patient until then :-)

**Comment by PXke** [comment]
Okay ;)

**Comment by PXke** [comment]
I close this PR then.

**Pull request closed without merging**
