### PR TITLE
release: v1.0.0a22

### PR DESCRIPTION
**Pull request by jacquerie**
https://github.com/inveniosoftware/invenio-files-rest/issues/171 is happening on our production system, so a new release will fix the issue on our next deploy.

### CODE REVIEW

**Comment by jacquerie** [comment]
Build is a little flaky... I just restarted a couple of builds that passed on the PR but didn't pass on the push: https://travis-ci.org/inveniosoftware/invenio-files-rest/builds/313419051.

**Comment by nharraud** [comment]
Sorry I just pushed the tag. Without it it would not update pypi.

**Comment by nharraud** [comment]
Pypi is updated

**Comment by jacquerie** [comment]
> Sorry I just pushed the tag. Without it it would not update pypi.

Thanks! I thought it was the failing build...

**Pull request merged**
